spring.datasource.url=jdbc:postgresql://{{ psql_app_name }}:5432/{{ psql_db_name }}
spring.datasource.username={{ psql_user_name }}
spring.datasource.password={{ psql_user_passwd }}

jbpm.quartz.configuration=file:./config/jbpm-quartz.properties
quartz.clustered=false
quartz.datasource.username={{ psql_user_name }}
quartz.datasource.password={{ psql_user_passwd }}
quartz.datasource.url=jdbc:postgresql://{{ psql_app_name }}:5432/{{ psql_db_name }}
quartz.datasource.dbcp2.maxTotal=20

narayana.dbcp.maxTotal=20

logging.config=file:./config/logback-spring.xml
logging.level.org.jbpm.executor.impl=WARN
logging.level.org.apache.kafka.clients=WARN
logging.level.org.hibernate.orm.deprecation=ERROR
logging.level.com.redhat.naps.process=DEBUG
logging.level.org.jbpm.process.audit=ERROR
logging.level.ca.uhn.fhir.context=INFO

# TO-DO: org.jbpm.kie.services.impl.KModuleDeploymentService.processClassloader(KModuleDeploymentService.java:479)  is throwing warnings between kjar is deployed to kie-server
#    ie: WARN  [main] org.reflections.ReflectionUtils: could not get type for name org.springframework.web.reactive.result.view.RequestDataValueProcessor from any class loader
# although, these warning do seem benign
logging.level.org.reflections=ERROR

kafka.bootstrap-address={{ kafka_bootstrap_service }}:9092
kafka.group-id=pneumonia-processing
kafka.concurrency=5
listener.destination.observation-reported-event=topic-fhir-r4-observation



#####   kieserver   ##########
server.address=0.0.0.0
server.port=8080
kieserver.location=http://{{ application_name }}:8080/rest/server



#####   fhir-bpm-app   ##########
observation.deployment.id={{ kie_deployment_name }}-{{ kie_deployment_version }}
